default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: team2
  password: buckeyes
  host: localhost

development:
  <<: *default
  database: grader_management_development

test:
  <<: *default
  database: grader_management_test

production:
  <<: *default
  database: grader_management_production
  username: grader_management
  password: <%= ENV["GRADER_MANAGEMENT_DATABASE_PASSWORD"] %>

new_development:
  <<: *default
  database: new_grader_management_development

new_test:
  <<: *default
  database: new_grader_management_test

new_production:
  <<: *default
  database: new_grader_management_production
  username: new_grader_management
  password: <%= ENV["NEW_GRADER_MANAGEMENT_DATABASE_PASSWORD"] %>
